Traceback (most recent call last):
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
output = model.run()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModelRunError[0m                             Traceback (most recent call last)
[0;32m~/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py[0m in [0;36m_run_step[0;34m(step)[0m
[1;32m    246[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 247[0;31m             [0;32mreturn[0m [0mgetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mstep[0m[0;34m)[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    248[0m         [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    350[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 351[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mmethod[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    352[0m [0;34m[0m[0m

[0;32m~/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/active_deterministic_base.py[0m in [0;36m_model_claim_cost[0;34m(self)[0m
[1;32m    282[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 283[0;31m             [0;32mraise[0m [0mModelRunError[0m[0;34m([0m[0mstr[0m[0;34m([0m[0merrors[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    284[0m [0;34m[0m[0m

[0;31mModelRunError[0m: [Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2015-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2016-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2017-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2018-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2019-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2020-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2021-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2022-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2023-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2024-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2025-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2026-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2027-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2028-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2029-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2030-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2031-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2032-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2033-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2034-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']')]

During handling of the above exception, another exception occurred:

[0;31mModelRunError[0m                             Traceback (most recent call last)
[0;32m<ipython-input-2-26c491dd16c9>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0moutput[0m [0;34m=[0m [0mmodel[0m[0;34m.[0m[0mrun[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py[0m in [0;36mrun[0;34m(self, to_step)[0m
[1;32m    306[0m [0;34m[0m[0m
[1;32m    307[0m         """
[0;32m--> 308[0;31m         [0;32mreturn[0m [0m_run[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mto_step[0m[0;34m=[0m[0mto_step[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    309[0m [0;34m[0m[0m
[1;32m    310[0m [0;34m[0m[0m

[0;32m~/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py[0m in [0;36m_run[0;34m(self, to_step)[0m
[1;32m    255[0m [0;34m[0m[0m
[1;32m    256[0m     [0;32mfor[0m [0mstep[0m [0;32min[0m [0msteps[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 257[0;31m         [0m_run_step[0m[0;34m([0m[0mstep[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    258[0m [0;34m[0m[0m
[1;32m    259[0m     [0;32mif[0m [0mto_step[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py[0m in [0;36m_run_step[0;34m(step)[0m
[1;32m    252[0m             [0mmsg[0m [0;34m+=[0m [0;34mf"  Error Message = {exc_value}\n"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    253[0m             [0mmsg[0m [0;34m+=[0m [0;34mf"  Error Trace = {format_list(extract_tb(exc_trace))}\n"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 254[0;31m             [0;32mraise[0m [0mModelRunError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    255[0m [0;34m[0m[0m
[1;32m    256[0m     [0;32mfor[0m [0mstep[0m [0;32min[0m [0msteps[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModelRunError[0m: At step [_model_claim_cost], an error occured.
  Error Type = ModelRunError
  Error Message = [Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2015-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2016-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2017-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2018-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2019-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2020-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2021-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2022-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2023-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2024-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2025-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2026-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2027-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2028-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2029-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2030-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2031-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2032-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2033-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2034-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']')]
  Error Trace = ['  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\n    return getattr(self, step)()\n', '  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\n    return self.method(*args, **kwargs)\n', '  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/active_deterministic_base.py", line 283, in _model_claim_cost\n    raise ModelRunError(str(errors))\n']

ModelRunError: At step [_model_claim_cost], an error occured.
  Error Type = ModelRunError
  Error Message = [Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2015-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2016-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2017-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2018-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2019-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2020-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2021-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2022-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2023-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2024-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2025-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2026-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2027-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2028-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2029-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2030-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2031-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2032-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2033-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']'), Error(key="({'policy_id': 'policy-1', 'valuation_dt': Timestamp('2034-06-02 00:00:00')},)", error_type='ModelRunError', error_value='(\'At step [_calculate_discount], an error occured.\\n  Error Type = TypeError\\n  Error Message = calc_discount() got an unexpected keyword argument \\\'t_adj\\\'\\n  Error Trace = [\\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\\\\n    return getattr(self, step)()\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\\\\n    return self.method(*args, **kwargs)\\\\n\\\', \\\'  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/disabled_deterministic_base.py", line 262, in _calculate_discount\\\\n    self.frame["DISCOUNT_BD"] = calc_discount(\\\\n\\\']\\n\',)', error_stacktrace='[\'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/jigs.py", line 84, in wrapper\\n    ret = self.model(**model_kwargs).run()\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 308, in run\\n    return _run(self, to_step=to_step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 257, in _run\\n    _run_step(step)\\n\', \'  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 254, in _run_step\\n    raise ModelRunError(msg)\\n\']')]
  Error Trace = ['  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 247, in _run_step\n    return getattr(self, step)()\n', '  File "/home/runner/work/footings-idi-model/footings-idi-model/.venv/lib/python3.8/site-packages/footings/model.py", line 351, in __call__\n    return self.method(*args, **kwargs)\n', '  File "/home/runner/work/footings-idi-model/footings-idi-model/src/footings_idi_model/policy_models/active_deterministic_base.py", line 283, in _model_claim_cost\n    raise ModelRunError(str(errors))\n']


